"""Build a standalone Agent from the current modular implementation.

Run ``python tools/bundle_agent.py``. The generated file is intended to be
copied to the pack root as ``agent.py``, next to ``data/change_tariff.csv``.
"""

import ast
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "dist" / "agent_single.py"
MODULES = (
    "__init__",
    "priors",
    "priors_history",
    "cells",
    "bayes",
    "planner",
    "llm_advisor",
    "explorer",
    "v4",
)
AGENT_IMPORTS = (
    "from agent_core import priors_history\n",
    "from agent_core.bayes import Posterior\n",
    "from agent_core.cells import build_cells\n",
    "from agent_core.explorer import Explorer\n",
    "from agent_core.llm_advisor import LLMAdvisor\n",
    "from agent_core.planner import Planner, safety_campaign\n",
    "from agent_core.priors import set_prior_source\n",
    "from agent_core.v4 import ExplorerV4, PlannerV4\n",
)


def replace_once(source: str, old: str, new: str, label: str) -> str:
    if source.count(old) != 1:
        raise ValueError(f"Expected exactly one {old!r} in {label}")
    return source.replace(old, new)


def bundle() -> str:
    sections = [
        '"""Standalone Beeline agent, generated by tools/bundle_agent.py."""',
    ]
    for name in MODULES:
        path = ROOT / "agent_core" / f"{name}.py"
        source = path.read_text(encoding="utf-8")
        if name == "priors_history":
            # The bundle lives in the pack root when used as agent.py.
            source = replace_once(
                source,
                'Path(__file__).resolve().parent.parent / "data"',
                'Path(__file__).resolve().parent / "data"',
                name,
            )
            # priors.py also defines get_prior; keep both implementations.
            source = replace_once(source, "def get_prior(cell, target):",
                                  "def get_history_prior(cell, target):", name)
        elif name == "bayes":
            source = replace_once(source, "from .priors import get_prior\n", "", name)
        elif name == "v4":
            for line in ("from .explorer import ROUND1_N, ROUND2_N, Explorer\n",
                         "from .planner import Planner, _best_assignment\n"):
                source = replace_once(source, line, "", name)
        elif name == "explorer":
            for line in ("from .llm_advisor import arm_id\n", "from .planner import FINAL_K\n",
                         "from .priors import get_prior\n"):
                source = replace_once(source, line, "", name)
        ast.parse(source, filename=str(path))
        sections.append(f"# --- agent_core/{name}.py ---\n{source.rstrip()}")

    agent_path = ROOT / "agent.py"
    agent = agent_path.read_text(encoding="utf-8")
    for import_line in AGENT_IMPORTS:
        agent = replace_once(agent, import_line, "", "agent.py")
    agent = replace_once(agent, "priors_history.get_prior",
                         "get_history_prior", "agent.py")
    sections.append(f"# --- agent.py ---\n{agent.rstrip()}")
    output = "\n\n".join(sections) + "\n"
    ast.parse(output, filename=str(OUTPUT))
    if "from agent_core" in output or "from ." in output:
        raise ValueError("Bundle still has package imports")
    return output


def main() -> None:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(bundle(), encoding="utf-8")
    print(OUTPUT)


if __name__ == "__main__":
    main()
